services:
  - type: web
    name: cenlearn-ml-api
    runtime: python
    rootDir: ml_api
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
